### PR TITLE
config feature initial - discussion

### PR DESCRIPTION
**Pull request by saminarp**
Hello,

I just started working on your project. I have a question:

As lab4 requires us to provide config file which is in json format, I need to use the following library [nlohmann/json](https://github.com/nlohmann/json). Could you help me insert this library like the way you did for argparser and termcolor? Thanks!

### CODE REVIEW

**Comment by batunpc** [comment]
Hello @saminarp 

I have just recently updated the repo including the nlohmann/json library for you using CMake. See the commit [here](https://github.com/batunpc/palpatine/commit/d44061b5ba7e57850cbeee70210a1f57da52a91c#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584) Also if you are curious on how to add libraries using CMake, you can read the docs [here](https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html). Simply project `palpatine` has a file `AddGitSubModule.cmake` withing the directory `cmake` This is a cmake function that lets you add libraries by just typing the following `add_git_submodule("external/<libname here>")`. (i.e external is the directory I created to keep all this kind of third party libraries)

Good luck let me know if any questions arises!

**Comment by batunpc** [comment]
Also I am working on the netlify fix, please ignore the checks

**Comment by saminarp** [comment]
Follow up to your comment above, I am having trouble accessing the `nlohmann json` library. After further investigating I noticed wrong git submodule has been imported. Could you take a look ?
Thank you

**Comment by batunpc** [comment]
@saminarp fixed by https://github.com/batunpc/palpatine/commit/bf2089a49ca4fb7c4912fb5e311d07fc00eb079d 
Please try again

**Comment by saminarp** [comment]
thanks for the merge!

**Pull request merged**
